// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "5O7cOSaYO6QBi5isUfbY8reNiI7plKiognnswzpVUN2U7iTHPOHnhGkK2l13Muizx1zuf2";
}
}
}

